# Description: This file contains the dependencies required to run the project.
#
# Command for generating listing installed package versions:
# https://github.com/conda/conda/issues/10345#issuecomment-1852838493

name: hslu-thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11  # Specify your desired Python version
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - python-dotenv
  - jupyter
  - langchain
  - langchain-openai
  - langchain-anthropic
  - langchain-community
  - langchain-google-genai
  - langchain-huggingface
  - langchain-mistralai
  - huggingface_hub
  - openai  # OpenAI API, used for fine-tuning
  - streamlit
  - pip
